config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :tasks do
    resources :todos, except: %i[index show] do
      patch 'toggle_done/todo'
      resources :details, except: %i[index show]
    end
  end
  root 'pages#index'
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :task
  has_many :details, dependent: :destroy
  
  validates :name, presence: true, uniqueness: {scope: :task_id }
  scope :ordered, -> { order(name: :asc) }
  def previous_todo
    task.todos.ordered.where('name < ?', name).last
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_task
  before_action :set_todo, only: [:edit, :update, :destroy]

  # def show
  #   @todos = @task.todos.ordered
  # end

  def new
    @todo = @task.todos.build
  end

  
  def create
    @todo = @task.todos.build(todo_params)

    if @todo.save
      respond_to do |format|
        format.html { redirect_to task_path(@task), notice: 'Todo was successfully created.' }
        format.turbo_stream { flash.now[notice:] = 'Todo was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end

  def update
    if @todo.update(todo_params)
      respond_to do |format|
        format.html { redirect_to task_path(@task), notice: 'Todo was successfully updated.'}
        format.turbo_stream { flash.now[:notice] = 'Todo successfully updated'}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to task_path(@task), notice: 'Todo deleted successfully. Ciao cacao' }
      format.turbo_stream { flash.now[:notice] = 'Todo deleted successfully. Ciao cacao' }
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :done, :task_id)
  end

  def set_task
    @task = current_team.tasks.find(params[:task_id])
  end

  def set_todo
    @todo = @task.todos.find(params[:id])
  end
end

app/views/todos/_form.html.erb
<%= simple_form_for [task, todo], html: { class: "form todo" } do |f| %>
    <%= form_error_notification(todo) %>

    <%= f.label :name %>
    <%= f.text_field :name, html5: true, input_html: { autofocus: true } %>

  <div class="todo__actions">
    <%= link_to "Cancel", task_path(task), class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo do %>
  <div class="todo <%= 'todo-done' if todo.done %>">
    <%= turbo_frame_tag dom_id(todo, :edit) do %>
      <div class="todo__header">
        <h2 class="todo__title">
            <%= check_box_tag :done, todo.done, todo.done,
              data: {
                controller:'toggle-done',
                action:"click->toggle-done#toggle",
                id: todo.id,
                task_id: task.id
              } %>
            <%= todo.name %>
            
        </h2>
        
       
        <div class="todo__actions">
          <%= link_to task_todo_path(task, todo), data: {turbo_method: :delete},
                        form: { data: {turbo_confirm: 'Sure?' } },
                        class: "btn btn--light btn-img btn-remove" do %><%= image_tag 'remove.svg', alt: 'Delete' %><% end %>
          <%= link_to edit_task_todo_path(task, todo),
                      class: "btn btn--light btn-img btn-edit" do %><%= image_tag 'edit.svg', alt: 'Edit' %><% end %>
        </div>
      </div>
    <%  end %>

    <div class="todo__body">
        <div class="detail detail--header">
          <div class="detail__name">Name</div>
          <div class="detail__description">Description</div>
          <div class="detail__time">Time</div>
          <div class="detail__actions"></div>
        </div>


      <%= turbo_frame_tag nested_dom_id(todo, "details") do %>
        <%= render todo.details, task: task, todo: todo %>
      <% end %>

      
      <%= turbo_frame_tag nested_dom_id(todo, Detail.new) %>

      <div class="todo__footer">
        <% if todo.done %>
          All the details of this todo have been completed. Delete this todo or edit it as undone to add more details.
        <% else %>
          <%= link_to "Add detail",
                          [:new, task, todo, :detail],
                          data: { turbo_frame: nested_dom_id(todo, Detail.new )},
                          class: "btn btn--primary" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.update Todo.new, '' %>

 

<%# Step 2: add the date at the right place %>
<% if previous_todo = @todo.previous_todo %>
  <%= turbo_stream.after previous_todo do %>
    <%= render @todo, task: @task %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "todos" do %>
    <%= render @todo, task: @task %>
  <% end %>
<% end %>


<%= render_turbo_stream_flash_messages %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo %>
<%= render_turbo_stream_flash_messages %>


<%= turbo_stream.update dom_id(@task, :total) do %>
  <%= render 'tasks/total', task: @task %>
<% end %>

app/views/todos/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to task"), task_path(@task) %>

  <div class="header">
    <h1>Edit name</h1>
  </div>

  <%= turbo_frame_tag dom_id(@todo, :edit) do %>
    <%= render "form", task: @task, todo: @todo %>
  <% end %>
</main>

app/views/todos/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to task"), task_path(@task) %>

  <div class="header">
    <h1>New todo</h1>
  </div>
  <%= turbo_frame_tag @todo do %>
    <%= render "form", task: @task, todo: @todo %>
  <% end%>
</main>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.remove @todo %>

<% if previous_todo = @todo.previous_todo %>
  <%= turbo_stream.after previous_todo do %>
    <%= render @todo, task: @task %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "todos" do %>
    <%= render @todo, task: @task %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>